import Head from 'next/head'
import Layout from '@/components/Layout'
import Image from 'next/image'
import Link from 'next/link'
import AnimatedText from '@/components/AnimatedText'
import TransitionEffect from '@/components/TransitionEffect'
import { LinkArrow } from '@/components/Icons'
import profilePic from "../../public/images/profile/image.png"
import HireMe from '@/components/HireMe'
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Muskan Arora's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light dark:bg-dark'>
        <Layout className='pt-0 md:pt-16 sm:pt-8 dark:bg-dark'>
          <div className="flex flex-col items-center justify-between w-full lg:flex-row">
            <div className='w-full lg:w-1/2'>
              <Image
                src={profilePic}
                alt="MA"
                className='w-full h-auto'
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>

            <div className='w-full lg:w-1/2 flex flex-col items-center self-center'>

              <AnimatedText
                text="Architecting Robust Systems & Intelligent Web Solutions"
                className='!text-6xl !text-left 
                xl:!text-7xl lg:!text-6xl md:!text-5xl sm:!text-3xl'
              />

              <p className='my-4 text-base font-medium text-left md:text-sm sm:text-xs text-center lg:text-left'>
                I am a Software Development Engineer with a specialized focus on Full-Stack architecture and AI integration.
                With a Master’s in Computer Science and hands-on experience optimizing financial platforms and educational AI tools,
                I turn complex data into intuitive, high-performance applications using Java, Python, and Spring Boot.
              </p>

              <div className='flex items-center self-center lg:self-start mt-2'>
                <Link href="/resume/Muskan_Resume.pdf" target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark 
                  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link href="mailto:muskan1999arora10@gmail.com" target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <div className='md:flex hidden'>
          <HireMe />
        </div>
        <div className='absolute right-8 bottom-8 md:inline-block w-24 hidden'>
          <Image src={lightBulb} alt='MA' className='w-full h-auto' />
        </div>
      </main>
    </>
  )
}